### ISSUE TITLE
About creat_gridpoint.m

### ISSUE THREAD

**Issue by zhao-xigua** [EuanPyle/Membrane_Associated_Picking#3]
Hi,Euan
I encountered a problem about "unrecognized function or variable 'dread‘ "，I found it’s not a matlab built-in functions, and in your scripts, I couldn't found a self-definition function. 
My goal is that I have a surface from your guideline now, I only want to use your script to compute normals, so I only run your creat_gridpoint.m , but I got this error. 
Can you help me ? thank you very much!

**Comment by EuanPyle** [comment]
Hi, dread is a Dynamo function, it sounds like Dynamo is not loaded correctly. Usually running a dynamo_activate.m script will load Dynamo for you. If it still doesn't work it will be a Dynamo installation issue

**Comment by zhao-xigua** [comment]
Yes, you're right! I'll try it later.
